workspace:
  base: /workspace

clone:
  sample-helloworld.git:
    image: index.qiniu.com/spock/git-plugin:cs-proxy
    path: /workspace/sample-helloworld
    depth: 1

pipeline:
  build:
    image: index.qiniu.com/spock/golang:1.7
    commands:
      - if [ -f /workspace/node_modules/test.log ]; then cat /workspace/node_modules/test.log; fi
      - cd /workspace/sample-helloworld
      - mkdir -p node_modules
      - echo `date` > /workspace/node_modules/test.log
      - make build
      - make test
      - echo "test 1"
      
    volumes:
      - /tmp/node_modules:/workspace/node_modules
  publish:
    image: index.qiniu.com/spock/docker-client
    pull: true
    commands:
      source <(curl -s http://spock.dev.qiniu.io/assets/env.sh)
