workspace:
  base: /workspace

cache:
  mount:
    - /workspace/cache

clone:
  sample-helloworld.git:
    image: index.qiniu.com/spock/git-plugin:cs-proxy
    path: /workspace/sample-helloworld
    depth: 1
    debug: true

pipeline:
  build:
    image: index.qiniu.com/spock/golang:1.7
    commands:
      - cat /workspace/cache/test.log
      - echo `date` > /workspace/cache/test.log
      - make build
      - make test
