workspace:
  base: /workspace

clone:
  sample-helloworld.git:
    image: index.qiniu.com/spock/git-plugin:cs-proxy
    path: /workspace/sample-helloworld
    depth: 1

pipeline:
  build:
    image: index.qiniu.com/spock/golang:1.7
    commands:
      - if [ -f /workspace/test/demo.log ]; then cat /workspace/test/demo.log; fi
      - cd /workspace/sample-helloworld
      - mkdir -p test
      - echo `date` > /workspace/test/test.log
      - make build
      - make test
      
    volumes:
      - /cache/test:/workspace/test
