workspace:
  base: /workspace

clone:
  sample-helloworld.git:
    image: index.qiniu.com/spock/git-plugin:cs-proxy
    path: /workspace/sample-helloworld

pipeline:
  build:
    image: index.qiniu.com/spock/golang:1.7
    commands:
      - if [ -f /workspace/test/demo.log ]; then cat /workspace/test/demo.log; fi
      - cd /workspace/sample-helloworld
      - mkdir -p test
      - echo `date` > /workspace/test/test.log
      - make build
      - make test
    volumes:
      - /cache/test:/workspace/test
  publish:
    image: index.qiniu.com/spock/docker-client
    pull: true
    commands:
      - curl -s http://spock.dev.qiniu.io/assets/env.sh -o env.sh && source ./env.sh
      - echo $SERVICE
      - echo $TAG
    
