clone:
  sample-helloworld.git:
    image: index.qiniu.com/spock/git-plugin:cs-proxy
    depth: 1
    debug: true

pipeline:
  build:
    image: index.qiniu.com/spock/golang:1.7
    commands:
      - make build
      - make test
      - cat .drone.yml
     when:
      commit_message: abc
    
