clone:
  sample-helloworld.git:
    image: index.qiniu.com/spock/git-plugin:cs-proxy
    depth: 1
    debug: true

pipeline:
  build:
    image: index.qiniu.com/spock/golang:1.7
    pull: true
    commands:
      - echo "hello dashu~"
      - echo $WHO
      - cat .drone.yml
      - make build
      - make test
      - printenv
      - if [[ $CI_COMMIT_MESSAGE =~ .*SVC=abc.* ]]; then echo "found" ;fi;
