workspace:
  base: /workspace

matrix:
  GO_VERSION:
    - 1.7
    - 1.7.4

clone:
  sample-helloworld.git:
    image: index.qiniu.com/spock/git-plugin:cs-proxy
    path: /workspace/sample-helloworld
    depth: 1
    debug: true

pipeline:
  build:
    image: index.qiniu.com/spock/golang:${GO_VERSION}
    commands:
      - make build
      - make test
