clone:
  sample-helloworld.git:
    image: index.qiniu.com/spock/git-plugin:cs-proxy
    depth: 1
    debug: true

pipeline:
  build:
    image: index.qiniu.com/spock/golang:1.7
    commands:
      - make build
      - make test
      - printenv
      - if [[ $CI_COMMIT_MESSAGE =~ .abc. ]]; then echo "It's there!" fi
