workspace:
  base: /workspace

clone:
  sample-helloworld.git:
    image: index.qiniu.com/spock/git-plugin:cs-proxy
    path: /workspace/sample-helloworld
    depth: 1

pipeline:
  build:
    image: index.qiniu.com/spock/golang:1.7
    commands:
      - if [ -f /workspace/cache/test.log ]; then cat /workspace/cache/test.log; fi
      - cd /workspace/sample-helloworld
      - mkdir -p node_modules
      - echo `date` > /workspace/cache/test.log
      - make build
      - make test
      - sleep 999
      
    volumes:
      - /cache/node_modules:/workspace/node_modules
