pipeline:
    clone:
        git:
            image: index.qiniu.com/qiniu-spock/git-plugin
            pull: true
            git_access_token: ${GIT_ACCESS_TOKEN}
            secrets: [ git_access_token ]

    build:
        image: golang:1.7
        commands:
        - echo ${GIT_ACCESS_TOKEN}
        - sleep 999
        secrets: [ git_access_token ]