pipeline:
    clone:
        image: index.qiniu.com/qiniu-spock/git-plugin
        remote_url: https://github.com/qbox/base.git
        depth: 1
        path: /workspace/base
        branch: develop

    build:
        image: golang:1.7
        commands:
        - find .