workspace:
    base: /workspace
pipeline:
    clone:
        image: plugins/git
        remote: https://github.com/yaoshipu/sample-helloworld.git
    build:
        image: golang:1.7
        commands:
        - ls