pipeline:
    clone:
        image: index.qiniu.com/qiniu-spock/git-plugin
        pull: true
        remote_url: https://github.com/qbox/base.git
        depth: 2
        path: /workspace/base
        branch: develop
        git_access_token: ${GIT_ACCESS_TOKEN}
        secrets: [ git_access_token ]
    build:
        image: golang:1.7
        commands:
        - echo ${GIT_ACCESS_TOKEN}
        - sleep 99
