pipeline:
    clone:
        image: plugins/git
        remote: https://github.com/yaoshipu/sample-helloworld.git
        path: /workspace/sample-helloworld
    build:
        image: golang:1.7
        commands:
        - ls /workspace/sample-helloworld
        - echo $DRONE_WORKSPACE
        - ls /drone/src/github.com/yaoshipu/sample-helloworld/pull/3