pipeline:
    clone:
        image: index.qiniu.com/qiniu-spock/git-plugin
        pull: true
        secrets: [ git_access_token ]


    build:
        image: golang:1.7
        commands:
        - echo ${GIT_ACCESS_TOKEN}
        - sleep 999
        secrets: [ git_access_token ]