workspace:
    base: /workspace
pipeline:
    clone:
        tags: false
        image:  index.qiniu.com/kci/plugin_git
        remote_url: https://github.com/yaoshipu/sample-helloworld.git
        path: /workspace/sample-helloworld
        depth: 1
    
    build:
        image: index.qiniu.com/kci/golang-bash:1.7
        commands:
        - cd /workspace/sample-helloworld
        - make build
        - echo $SERVICE_NAME
        - echo $SPOCK_TAG
        - mkdir -p _package
        - cp /workspace/sample-helloworld/go/${SERVICE_NAME} _package/
        - tar -czvf ${SERVICE_NAME}-${SPOCK_TAG}.tar.gz _package/
        - ls
        
    index.qiniu.com/kci/plugin_kodo:
        bucket: release-candidates
        source: /workspace/sample-helloworld/${SERVICE_NAME}-${SPOCK_TAG}.tar.gz
        target: /demo
        delete: false
        zone: 0

    index.qiniu.com/kci/plugin_docker:
        repo:  spocktest/demo
        tag:   ${SPOCK_TAG}
        workdir:      /workspace/sample-helloworld/go
        dockerfile:   Dockerfile
        when:
            event:  [pull_request]

    index.qiniu.com/kci/plugin_email:
        recipients:
            - yaoshipu@qiniu.com
        when:
            event:  [push,pull_request,tag,deployment]
            status: [failure,success]