pipeline:
    clone:
        image: index.qiniu.com/qiniu-spock/git-plugin:latest
        secrets: [ REGISTRY_USERNAME, REGISTRY_PASSWORD ]
        remote url: https://github.com/qbox/base.git
        depth: 1

    build:
        image: golang:1.7
        commands:
        - find .