pipeline:
    clone:
        image: index.qiniu.com/qiniu-spock/git-plugin
        pull: true
        remote_url: https://github.com/qbox/base.git
        depth: 1

    build:
        image: golang:1.7
        commands:
        - find .