workspace:
    base: /workspace
pipeline:
    clone:
        tags: false
        image:  index.qiniu.com/kci/plugin_git
        remote_url: https://github.com/yaoshipu/sample-helloworld.git
        path: /workspace/sample-helloworld
        ref: refs/heads/master
        depth: 1
    
    build:
        image: index.qiniu.com/kci/golang-bash:1.7
        commands:
        - cd /workspace/sample-helloworld
        - make build
        
    index.qiniu.com/kci/plugin_kodo:
        bucket: release-candidates
        source: /workspace/sample-helloworld/go/helloworld
        target: /test
        delete: false
        zone: 0

    index.qiniu.com/kci/plugin_docker:
        repo:  spocktest/helloworld
        tag:   latest
        workdir:      /workspace/sample-helloworld/go
        dockerfile:   Dockerfile
        when:
            event:  [pull_request]

    index.qiniu.com/kci/plugin_email:
        recipients:
            - yaoshipu@qiniu.com
        when:
            event:  [push,pull_request,tag,deployment]
            status: [failure,success]